languageCode = 'nb-NO'
title = 'Balestrand Fjord Apartments'
theme = 'boilerplate-hugo-theme'

defaultContentLanguage = 'nb'



[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 80
  resampleFilter = 'MitchellNetravali'

[languages]
  [languages.nb]
    languageName = "Norsk"
    weight = 1
    other = "Norsk"
  [languages.en]
    languageName = "English"
    weight = 2
    other = "English"
  [languages.de]
    languageName = "Deutsch"
    weight = 3
    other = "Deutsch"



[Params]
  ogimage = '/images/balestrand.jpg'


