languageCode = 'nb-NO'
title = 'Balestrand Fjord Apartments'
theme = 'boilerplate-hugo-theme'

defaultContentLanguage = 'no'

baseURL = "https://www.fjordapartments.no/"

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 80
  resampleFilter = 'MitchellNetravali'

[languages]
  [languages.no]
    languageName = "Norsk"
    weight = 1
    other = "Norsk"
  [languages.en]
    languageName = "English"
    weight = 2
    other = "English"
  [languages.de]
    languageName = "Deutsch"
    weight = 3
    other = "Deutsch"

[Params]
  ogimage = "https://fjordapartments.no/images/IMG_6391.jpeg"
  keywords = ['Fjordapartments', 'Balestrand', 'Vestland']
  email = "lidalsiv@gmail.com"
