disableKinds = ["taxonomy","taxonomyTerm"]

languageCode = 'nb-NO'
title = 'Balestrand Fjord Apartments'
theme = 'boilerplate-hugo-theme'

defaultContentLanguage = 'no'

baseURL = "https://www.fjordapartments.no/"

canonifyURLs = true

enableRobotsTXT = true

[minify]
  minifyOutput = true

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 75
  resampleFilter = 'MitchellNetravali'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[languages]
  [languages.no]
    languageName = "Norsk"
    weight = 1
    other = "Norsk"
  [languages.en]
    languageName = "English"
    weight = 2
    other = "English"
  [languages.de]
    languageName = "Deutsch"
    weight = 3
    other = "Deutsch"

[Params]
  ogimage = "https://fjordapartments.no/images/holmen_hu5c462718f5c094e8219d8230346b031d_520206_400x275_fill_q100_mitchellnetravali_smart1.jpg"
  keywords = ['Fjordapartments', 'Balestrand', 'Vestland']
  email = "lidalsiv@gmail.com"
